### ISSUE TITLE
[Help] ==> Did you mean C:\Users\User\.drone\drone-hive\hive\reactivex\rxandroid

### ISSUE THREAD

**Issue by ferbeb** [cesarferreira/drone#10]
`λ drone add reactivex/rxandroid app`

> ==> Did you mean
> C:\Users\User\.drone\drone-hive\hive\reactivex\rxandroid

I don't know, did I?

**Comment by cesarferreira** [comment]
Hmmm, it looks like you're using windows, I don't own any windows machine, can't replicate it :/
It looks like something is wrong with the path to the `hive` on windows

I'll put the `help wanted` tag on this issue.
