### ISSUE TITLE
Add to wrong place

### ISSUE THREAD

**Issue by alahammad** [cesarferreira/drone#13]
Hi ,
I tried to add picasso library using drone but in same I have already added fabric and as you know fabric add classpath as follow :

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }

so after I added picasso using drone this what happened 

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    compile 'com.squareup.picasso:picasso:2.5.2'
    }

not in correct place .

**Comment by cesarferreira** [comment]
hi, did you specify the `module`?

**Comment by alahammad** [comment]
yes, my command was 

drone add square/retorfit app

**Comment by cesarferreira** [comment]
Can you show me your `/build.gradle` and `app/build.gradle` (you can omit the irrelevant parts)
So i can try to reproduce and fix it?

**Comment by alahammad** [comment]
`buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "net.ahammad.braingame"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 16
        versionName "1.0.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.google.android.gms:play-services-games:11.4.0'
    compile 'com.github.bumptech.glide:glide:4.0.0'
    compile 'com.android.support:gridlayout-v7:26.1.0'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
}`

**Comment by cesarferreira** [comment]
I see what the problem is, I'll look into it when I have a little bit of time, thanks :)
