### ISSUE TITLE
Thought about new api and implementation in android gradle plugin 3.0? 

### ISSUE THREAD

**Issue by esafirm** [cesarferreira/drone#14]
As the title stated, what do you think about it? Because now it's based on the compile line user inputted to hive (CMIIW)

**Comment by cesarferreira** [comment]
Hey, yeah I thought about it a lot and as of this time the gradle plugin that enforces `implementation` over `compile` is still in beta, once it goes stable I'll do a quick find and replace and publish a new version.

Do you have any other suggestion?

**Comment by esafirm** [comment]
I think the user should be able to choose between `implementation` and `api`. But it would be cool if drone could pre-determine it. 

Like if the module is not a dependency to the others, it must(?) be an `implementation` 

Anyway, thanks for answering you can close it if you want. Cheers!
